### ISSUE TITLE
Xcode 11.4 build failed

### ISSUE THREAD

**Issue by HyEnjoys** [UrbanCompass/Snail#136]
<img width="1038" alt="截屏2020-03-26上午10 45 51" src="https://user-images.githubusercontent.com/19705592/77620420-49e7b480-6f75-11ea-912f-c5ed9becd110.png">

**Comment by russellbstephens** [comment]
Hi @HyEnjoys, thanks for your interest in the project.  We will take a look at the required fixes for the new XCode version shortly.

**Comment by lucaslain** [comment]
@HyEnjoys please take a look at the latest version `0.7.0`.

**Comment by HyEnjoys** [comment]
Thank you.
