### ISSUE TITLE
Installation Section

### ISSUE THREAD

**Issue by lfarah** [UrbanCompass/Snail#51]
Hey, your library is really interesting.

The only problem I found was the ```README.md```, which lacks an ```Installation Section```
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to easily create an ```Installation Section```
If you want, I can help you to organize the lib.

What are your thoughts? 😄

**Comment by lfarah** [comment]
Please fix this before [I can approve your PR](https://github.com/vsouza/awesome-ios/pull/1442)

**Comment by wesbillman** [comment]
Awesome, thanks @lfarah, we'll fix it up. We currently only support manual, carthage, and swiftPM, so I can update the README to include those. Would that be sufficient?

**Comment by lfarah** [comment]
Definitely 👍
