### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by lfarah** [UrbanCompass/Snail#52]
I'd be cool to also add CocoaPods support. I've done this implementation myself last week for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by lfarah** [comment]
Regarding #51: Not required for me to apporve the PR, but I wanted to leave this issue open for the future

**Comment by Exey** [comment]
Please add support of CocoaPods

**Comment by wesbillman** [comment]
@Exey and @lfarah thanks for the suggestions! If either of you want to submit a PR for cocoapods I would gladly review. I'm not 100% when I'll get to adding it myself though :)

**Comment by wesbillman** [comment]
@lfarah and @Exey I added a podspec today if you want to give it a try. https://cocoapods.org/pods/Snail
